# shellcheck shell=bash
# Moodle site: config.php, database, install, upgrade and optional extras.

MANAGED_CONFIG=/etc/moodle/oksigenia.php

# Decide where the database settings come from and write config.php.
# Native layout: config.php is generated from the environment at each start.
# Existing config.php from another setup (bitnami/moodle, a manual install):
# it is kept as the source of truth and only gains one include line.
prepare_config() {
    local config="${MOODLE_CODE_DIR}/config.php"
    if [ -f "${config}" ] && ! grep -q 'Generated by oksigenia/moodle' "${config}"; then
        OKS_CONFIG=foreign
        log "Using the existing config.php (database settings come from it)"
        local settings
        settings="$(php "${OKS_PHP}/read-config.php" "${config}")" || die "cannot read ${config}"
        eval "${settings}"
        export OKS_DB_TYPE OKS_DB_HOST OKS_DB_PORT OKS_DB_SOCKET OKS_DB_NAME OKS_DB_USER OKS_DB_PASSWORD OKS_DB_PREFIX
        if [ -n "${OKS_CFG_DATAROOT}" ] && [ "${OKS_CFG_DATAROOT}" != "${MOODLE_DATA_DIR}" ]; then
            warn "config.php sets dataroot to ${OKS_CFG_DATAROOT}, not ${MOODLE_DATA_DIR}; Moodle will use ${OKS_CFG_DATAROOT}"
        fi
        php "${OKS_PHP}/write-config.php" foreign "${MOODLE_CODE_DIR}" || die "cannot update ${config}"
    else
        OKS_CONFIG=native
        export OKS_DB_TYPE="${MOODLE_DB_TYPE}" OKS_DB_HOST="${MOODLE_DB_HOST}" OKS_DB_PORT="${MOODLE_DB_PORT}" \
            OKS_DB_SOCKET='' OKS_DB_NAME="${MOODLE_DB_NAME}" OKS_DB_USER="${MOODLE_DB_USER}" \
            OKS_DB_PASSWORD="${MOODLE_DB_PASSWORD}" OKS_DB_PREFIX="${MOODLE_DB_PREFIX}"
        php "${OKS_PHP}/write-config.php" native "${MOODLE_CODE_DIR}" || die "cannot write ${config}"
    fi
    export OKS_LAYOUT_CONFIG="${OKS_CONFIG}"
    if [ -z "${OKS_DB_PASSWORD}" ]; then
        if [ "${OKS_CONFIG}" = foreign ]; then
            warn "config.php has an empty database password; use this only for local testing"
        else
            warn "MOODLE_DB_PASSWORD is empty; use this only for local testing"
        fi
    fi
}

write_managed_config() {
    OKS_LAYOUT="${OKS_CONFIG}" php "${OKS_PHP}/write-config.php" managed "${MANAGED_CONFIG}" \
        || die "cannot write ${MANAGED_CONFIG}"
}

wait_for_database() {
    log "Connecting to the ${OKS_DB_TYPE} database at ${OKS_DB_HOST}:${OKS_DB_PORT}"
    # Transient: exit, so that a restart policy tries again.
    OKS_DB_WAIT="${MOODLE_DB_WAIT_TIMEOUT}" php "${OKS_PHP}/db.php" wait || { OKS_TRANSIENT=yes; exit 1; }
    OKS_DB_STATE="$(php "${OKS_PHP}/db.php" state)" || die "cannot inspect the database"
    case "${OKS_DB_STATE}" in
        installed|empty) ;;
        partial) die "the database has Moodle tables but no completed install (an earlier install failed?).
        Empty the database, or restore a backup, and start again." ;;
        *) die "unexpected database state: ${OKS_DB_STATE}" ;;
    esac
}

backup_database() {
    local out
    case "${OKS_DB_TYPE}" in
        pgsql)
            out="${OKS_BACKUP_DIR}/database.pgdump"
            log "Backing up the database to ${out}"
            PGPASSWORD="${OKS_DB_PASSWORD}" pg_dump --format=custom --no-owner \
                -h "${OKS_DB_HOST}" -p "${OKS_DB_PORT}" -U "${OKS_DB_USER}" -d "${OKS_DB_NAME}" -f "${out}" \
                || die "database backup failed; nothing was changed (set MOODLE_BACKUP_BEFORE_UPGRADE=off to skip it)"
            ;;
        *)
            out="${OKS_BACKUP_DIR}/database.sql.gz"
            log "Backing up the database to ${out}"
            local cnf
            cnf="$(mktemp)"
            chmod 0600 "${cnf}"
            printf '[client]\nhost=%s\nport=%s\nuser=%s\npassword="%s"\n' \
                "${OKS_DB_HOST}" "${OKS_DB_PORT}" "${OKS_DB_USER}" "${OKS_DB_PASSWORD//\"/\\\"}" > "${cnf}"
            if ! mariadb-dump --defaults-extra-file="${cnf}" --single-transaction --quick --routines \
                --skip-ssl-verify-server-cert --default-character-set=utf8mb4 "${OKS_DB_NAME}" | gzip -6 > "${out}"; then
                rm -f "${cnf}"
                die "database backup failed; nothing was changed (set MOODLE_BACKUP_BEFORE_UPGRADE=off to skip it)"
            fi
            rm -f "${cnf}"
            ;;
    esac
}

install_site() {
    local password="${MOODLE_ADMIN_PASSWORD:-}" generated=no
    if [ -z "${password}" ]; then
        password="$(head -c 18 /dev/urandom | base64 | tr -d '/+=' | cut -c1-20)Aa1!"
        generated=yes
    fi
    log "Installing Moodle in the database (this takes a few minutes)"
    local -a args=(
        --lang="${MOODLE_LANG}"
        --adminuser="${MOODLE_ADMIN_USER}"
        --adminpass="${password}"
        --adminemail="${MOODLE_ADMIN_EMAIL}"
        --fullname="${MOODLE_SITE_NAME}"
        --shortname="${MOODLE_SITE_SHORTNAME:-${MOODLE_SITE_NAME}}"
        --agree-license
    )
    [ -n "${MOODLE_SUPPORT_EMAIL:-}" ] && args+=(--supportemail="${MOODLE_SUPPORT_EMAIL}")
    moodle_php admin/cli/install_database.php "${args[@]}" || die "the Moodle install failed"

    # Settings that only apply to a new site: never touched again afterwards.
    local -a cfg=()
    [ -n "${MOODLE_NOREPLY_ADDRESS:-}" ] && cfg+=("noreplyaddress=${MOODLE_NOREPLY_ADDRESS}")
    [ -n "${MOODLE_TIMEZONE:-}" ] && cfg+=("timezone=${MOODLE_TIMEZONE}")
    if [ -n "${MOODLE_SMTP_HOST:-}" ]; then
        cfg+=("smtphosts=${MOODLE_SMTP_HOST}${MOODLE_SMTP_PORT:+:${MOODLE_SMTP_PORT}}")
        cfg+=("smtpuser=${MOODLE_SMTP_USER:-}" "smtppass=${MOODLE_SMTP_PASSWORD:-}")
        cfg+=("smtpsecure=${MOODLE_SMTP_SECURITY:-}")
    fi
    local kv
    for kv in "${cfg[@]}"; do
        moodle_php admin/cli/cfg.php --name="${kv%%=*}" --set="${kv#*=}" >/dev/null \
            || warn "could not set ${kv%%=*}"
    done

    if [ "${generated}" = yes ]; then
        log "------------------------------------------------------------------"
        log "Administrator: ${MOODLE_ADMIN_USER}"
        log "Generated password: ${password}"
        log "Change it after your first login, or set MOODLE_ADMIN_PASSWORD."
        log "------------------------------------------------------------------"
    fi
}

# A failed upgrade leaves a marker. Later starts stop right away instead of
# retrying in a restart loop, which would take a new backup of a half-upgraded
# database every time and rotate the good one away.
UPGRADE_FAILED_MARKER_NAME=upgrade-failed

check_failed_upgrade() {
    local marker="${OKS_DATA_STATE}/${UPGRADE_FAILED_MARKER_NAME}"
    [ -f "${marker}" ] || return 0
    if is_on "${MOODLE_RETRY_UPGRADE:-no}"; then
        warn "Retrying the upgrade that failed before (MOODLE_RETRY_UPGRADE is on)"
        rm -f "${marker}"
        OKS_RETRYING=yes
        return 0
    fi
    die "a previous upgrade failed and the site is in maintenance mode:
$(sed 's/^/        /' "${marker}")
        Fix the cause (see the error above in an earlier log), then start the container with
        MOODLE_RETRY_UPGRADE=yes, or delete ${marker}.
        Backups taken before that upgrade are in ${OKS_DATA_STATE}/backups"
}

# When retrying, drop the upgraderunning flag left by the failed attempt and
# the caches that may hold it; Apache is not running yet.
clear_failed_upgrade_flag() {
    [ "${OKS_RETRYING:-no}" = yes ] || return 0
    php "${OKS_PHP}/db.php" unset-config upgraderunning || true
    find "${MOODLE_DATA_DIR}/cache" "${MOODLE_DATA_DIR}/localcache" -mindepth 1 -maxdepth 1 \
        -exec rm -rf {} + 2>/dev/null || true
}

# The upgrade runs in CLI maintenance mode. A site that its administrator had
# already closed (CLI maintenance, the web setting, or a scheduled start)
# must not be opened by it: the state before is kept in a file until the
# upgrade succeeds, so a retry after a failure restores it too.
MAINTENANCE_BEFORE_NAME=maintenance-before

save_maintenance_state() {
    local file="${OKS_DATA_STATE}/${MAINTENANCE_BEFORE_NAME}" state="" later
    [ -f "${file}" ] && return 0
    [ -f "${OKS_CFG_DATAROOT:-${MOODLE_DATA_DIR}}/climaintenance.html" ] && state+="cli "
    [ "$(php "${OKS_PHP}/db.php" config maintenance_enabled)" = 1 ] && state+="web "
    later="$(php "${OKS_PHP}/db.php" config maintenance_later)" || later=""
    [ -n "${later}" ] && state+="later=${later} "
    printf '%s\n' "${state}" > "${file}"
}

restore_maintenance_state() {
    local file="${OKS_DATA_STATE}/${MAINTENANCE_BEFORE_NAME}" state="" later
    [ -f "${file}" ] && state=" $(cat "${file}")"
    if [[ "${state}" == *" cli "* ]]; then
        log "The site stays in maintenance mode, as it was before the upgrade. To open it: moodle-cli maintenance --disable"
    else
        moodle_php admin/cli/maintenance.php --disable >/dev/null || true
        if [[ "${state}" == *" web "* ]]; then
            moodle_php admin/cli/maintenance.php --enableold >/dev/null || true
            log "The site stays in maintenance mode for all but administrators, as it was before the upgrade"
        fi
        later="$(sed -n 's/.*later=\([0-9]*\).*/\1/p' <<< "${state}")"
        if [ -n "${later}" ]; then
            moodle_php admin/cli/cfg.php --name=maintenance_later --set="${later}" >/dev/null || true
            log "The maintenance mode scheduled before the upgrade is kept: it starts at $(date -u -d "@${later}" '+%Y-%m-%d %H:%M UTC')"
        fi
    fi
    rm -f "${file}"
}

upgrade_site() {
    local rc=0 out
    out="$(moodle_php admin/cli/upgrade.php --is-pending 2>&1)" || rc=$?
    case "${rc}" in
        0)
            # After a failed or interrupted upgrade that needs nothing more,
            # go back to the maintenance mode the site had before it.
            if [ "${OKS_RETRYING:-no}" = yes ] || [ -f "${OKS_DATA_STATE}/${MAINTENANCE_BEFORE_NAME}" ]; then
                restore_maintenance_state
                moodle_php admin/cli/purge_caches.php >/dev/null || true
            fi
            return 0
            ;;
        2) ;;
        *) printf '%s\n' "${out}" >&2; die "Moodle cannot start (upgrade check failed with code ${rc})" ;;
    esac
    is_on "${MOODLE_AUTO_UPGRADE}" \
        || die "the database needs an upgrade and MOODLE_AUTO_UPGRADE is off; run: moodle-cli upgrade"
    if is_on "${MOODLE_BACKUP_BEFORE_UPGRADE}" && [ "${OKS_DB_BACKED_UP:-no}" != yes ]; then
        backup_dir_new
        backup_database
    fi
    log "Upgrading the Moodle database"
    save_maintenance_state
    moodle_php admin/cli/maintenance.php --enable >/dev/null || true
    if ! moodle_php admin/cli/upgrade.php --non-interactive; then
        printf 'when: %s\nimage: Moodle %s\nbackups: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            "$(cat "${IMAGE_CODE}/.oksigenia-image-version")" "${OKS_BACKUP_DIR:-${OKS_DATA_STATE}/backups}" \
            > "${OKS_DATA_STATE}/${UPGRADE_FAILED_MARKER_NAME}"
        die "the database upgrade failed (error above). The site stays in maintenance mode.
        Backups are in ${OKS_DATA_STATE}/backups. Later starts will stop here until you fix
        the cause and start with MOODLE_RETRY_UPGRADE=yes."
    fi
    remove_deleted_standard_plugins
    moodle_php admin/cli/purge_caches.php >/dev/null || true
    restore_maintenance_state
    backup_rotate
    log "Database upgrade finished"
}

# Standard plugins that Moodle dropped from core stay registered with status
# "delete" when Moodle's own upgrade does not remove them. Uninstall the ones
# that hold nothing (blocks without instances, modules without activities),
# then let Moodle finish the upgrade it asks for afterwards.
remove_deleted_standard_plugins() {
    local plugins rc=0
    plugins="$(moodle_php "${OKS_PHP}/deleted-plugins.php" "${MOODLE_CODE_DIR}")" || return 0
    [ -n "${plugins}" ] || return 0
    log "Uninstalling standard plugins Moodle removed from core, unused here: ${plugins}"
    moodle_php admin/cli/uninstall_plugins.php --plugins="${plugins}" --run >/dev/null \
        || { warn "could not uninstall ${plugins}; uninstall them from Site administration > Plugins"; return 0; }
    moodle_php admin/cli/upgrade.php --is-pending >/dev/null 2>&1 || rc=$?
    if [ "${rc}" = 2 ]; then
        moodle_php admin/cli/upgrade.php --non-interactive >/dev/null \
            || warn "Moodle's upgrade after uninstalling ${plugins} failed; run: moodle-cli upgrade"
    fi
}

# Extra language packs: installed when the list changes.
sync_langs() {
    local wanted="${MOODLE_EXTRA_LANGS:-}" stamp="${OKS_DATA_STATE}/langs"
    [ -n "${wanted}" ] || return 0
    [ "$(cat "${stamp}" 2>/dev/null)" = "${wanted}" ] && return 0
    log "Installing language packs: ${wanted}"
    if moodle_php "${OKS_PHP}/langs.php" "${MOODLE_CODE_DIR}" "${wanted}"; then
        echo "${wanted}" > "${stamp}"
    else
        warn "some language packs could not be installed; retrying at the next start"
    fi
}

sync_redis_cache() {
    [ -n "${MOODLE_REDIS_HOST:-}" ] || return 0
    local stamp="${OKS_DATA_STATE}/redis" wanted="${MOODLE_REDIS_HOST}:${MOODLE_REDIS_PORT:-6379}"
    [ "$(cat "${stamp}" 2>/dev/null)" = "${wanted}" ] && return 0
    if moodle_php "${OKS_PHP}/redis-cache.php" "${MOODLE_CODE_DIR}"; then
        echo "${wanted}" > "${stamp}"
    else
        warn "could not configure the Redis application cache; retrying at the next start"
    fi
}

# Scripts in /docker-entrypoint-init.d run once, after the first install.
run_init_scripts() {
    local marker="${OKS_DATA_STATE}/init-scripts-done" script
    [ -d /docker-entrypoint-init.d ] || return 0
    [ -f "${marker}" ] || [ -f "${MOODLE_CODE_DIR}/.user_scripts_initialized" ] && return 0
    for script in /docker-entrypoint-init.d/*; do
        [ -f "${script}" ] || continue
        case "${script}" in
            *.sh)  log "Running ${script}"; as_www bash "${script}" || die "${script} failed" ;;
            *.php) log "Running ${script}"; moodle_php "${script}" || die "${script} failed" ;;
            *)     warn "Ignoring ${script} (only .sh and .php are run)" ;;
        esac
    done
    touch "${marker}"
}

# HTTPS on APACHE_HTTPS_PORT when certificates are mounted at /certs, and
# for bitnami/moodle layouts (which always served 8443) with a self-signed one.
setup_tls() {
    OKS_TLS=off
    local crt key
    for crt in /certs/tls.crt /certs/server.crt; do
        key="${crt%.crt}.key"
        if [ -r "${crt}" ] && [ -r "${key}" ]; then
            MOODLE_TLS_CERT="${crt}" MOODLE_TLS_KEY="${key}" OKS_TLS=on
            break
        fi
    done
    if [ "${OKS_TLS}" = off ] && [ "${OKS_LAYOUT}" = bitnami ]; then
        local dir="${OKS_DATA_STATE}/tls"
        if [ ! -f "${dir}/tls.crt" ]; then
            mkdir -p "${dir}"
            chmod 0700 "${dir}"
            openssl req -x509 -newkey rsa:2048 -nodes -days 1825 -subj "/CN=${APACHE_SERVER_NAME}" \
                -addext "subjectAltName=DNS:${APACHE_SERVER_NAME},IP:127.0.0.1" \
                -keyout "${dir}/tls.key" -out "${dir}/tls.crt" 2>/dev/null \
                || { warn "could not create a self-signed certificate; HTTPS is off"; return 0; }
        fi
        MOODLE_TLS_CERT="${dir}/tls.crt" MOODLE_TLS_KEY="${dir}/tls.key" OKS_TLS=on
    fi
    export OKS_TLS MOODLE_TLS_CERT MOODLE_TLS_KEY
}
