# shellcheck shell=bash
# Moodle site: config.php, database, install, upgrade and optional extras.

MANAGED_CONFIG=/etc/moodle/oksigenia.php

# Decide where the database settings come from and write config.php.
# Native layout: config.php is generated from the environment at each start.
# Existing config.php from another setup (bitnami/moodle, a manual install):
# it is kept as the source of truth and only gains one include line.
prepare_config() {
    local config="${MOODLE_CODE_DIR}/config.php"
    if [ -f "${config}" ] && ! grep -q 'Generated by oksigenia/moodle' "${config}"; then
        OKS_CONFIG=foreign
        log "Using the existing config.php (database settings come from it)"
        local settings
        settings="$(php "${OKS_PHP}/read-config.php" "${config}")" || die "cannot read ${config}"
        eval "${settings}"
        export OKS_DB_TYPE OKS_DB_HOST OKS_DB_PORT OKS_DB_SOCKET OKS_DB_NAME OKS_DB_USER OKS_DB_PASSWORD OKS_DB_PREFIX
        if [ -n "${OKS_CFG_DATAROOT}" ] && [ "${OKS_CFG_DATAROOT}" != "${MOODLE_DATA_DIR}" ]; then
            warn "config.php sets dataroot to ${OKS_CFG_DATAROOT}, not ${MOODLE_DATA_DIR}; Moodle will use ${OKS_CFG_DATAROOT}"
        fi
        php "${OKS_PHP}/write-config.php" foreign "${MOODLE_CODE_DIR}" || die "cannot update ${config}"
    else
        OKS_CONFIG=native
        export OKS_DB_TYPE="${MOODLE_DB_TYPE}" OKS_DB_HOST="${MOODLE_DB_HOST}" OKS_DB_PORT="${MOODLE_DB_PORT}" \
            OKS_DB_SOCKET='' OKS_DB_NAME="${MOODLE_DB_NAME}" OKS_DB_USER="${MOODLE_DB_USER}" \
            OKS_DB_PASSWORD="${MOODLE_DB_PASSWORD}" OKS_DB_PREFIX="${MOODLE_DB_PREFIX}"
        php "${OKS_PHP}/write-config.php" native "${MOODLE_CODE_DIR}" || die "cannot write ${config}"
    fi
    export OKS_LAYOUT_CONFIG="${OKS_CONFIG}"
}

write_managed_config() {
    OKS_LAYOUT="${OKS_CONFIG}" php "${OKS_PHP}/write-config.php" managed "${MANAGED_CONFIG}" \
        || die "cannot write ${MANAGED_CONFIG}"
}

wait_for_database() {
    log "Connecting to the ${OKS_DB_TYPE} database at ${OKS_DB_HOST}:${OKS_DB_PORT}"
    OKS_DB_WAIT="${MOODLE_DB_WAIT_TIMEOUT}" php "${OKS_PHP}/db.php" wait || exit 1
    OKS_DB_STATE="$(php "${OKS_PHP}/db.php" state)" || die "cannot inspect the database"
    case "${OKS_DB_STATE}" in
        installed|empty) ;;
        partial) die "the database has Moodle tables but no completed install (an earlier install failed?).
        Empty the database, or restore a backup, and start again." ;;
        *) die "unexpected database state: ${OKS_DB_STATE}" ;;
    esac
}

backup_database() {
    local out
    case "${OKS_DB_TYPE}" in
        pgsql)
            out="${OKS_BACKUP_DIR}/database.pgdump"
            log "Backing up the database to ${out}"
            PGPASSWORD="${OKS_DB_PASSWORD}" pg_dump --format=custom --no-owner \
                -h "${OKS_DB_HOST}" -p "${OKS_DB_PORT}" -U "${OKS_DB_USER}" -d "${OKS_DB_NAME}" -f "${out}" \
                || die "database backup failed; nothing was changed (set MOODLE_BACKUP_BEFORE_UPGRADE=off to skip it)"
            ;;
        *)
            out="${OKS_BACKUP_DIR}/database.sql.gz"
            log "Backing up the database to ${out}"
            local cnf
            cnf="$(mktemp)"
            chmod 0600 "${cnf}"
            printf '[client]\nhost=%s\nport=%s\nuser=%s\npassword="%s"\n' \
                "${OKS_DB_HOST}" "${OKS_DB_PORT}" "${OKS_DB_USER}" "${OKS_DB_PASSWORD//\"/\\\"}" > "${cnf}"
            if ! mariadb-dump --defaults-extra-file="${cnf}" --single-transaction --quick --routines \
                --skip-ssl-verify-server-cert --default-character-set=utf8mb4 "${OKS_DB_NAME}" | gzip -6 > "${out}"; then
                rm -f "${cnf}"
                die "database backup failed; nothing was changed (set MOODLE_BACKUP_BEFORE_UPGRADE=off to skip it)"
            fi
            rm -f "${cnf}"
            ;;
    esac
}

install_site() {
    local password="${MOODLE_ADMIN_PASSWORD:-}" generated=no
    if [ -z "${password}" ]; then
        password="$(head -c 18 /dev/urandom | base64 | tr -d '/+=' | cut -c1-20)Aa1!"
        generated=yes
    fi
    log "Installing Moodle in the database (this takes a few minutes)"
    local -a args=(
        --lang="${MOODLE_LANG}"
        --adminuser="${MOODLE_ADMIN_USER}"
        --adminpass="${password}"
        --adminemail="${MOODLE_ADMIN_EMAIL}"
        --fullname="${MOODLE_SITE_NAME}"
        --shortname="${MOODLE_SITE_SHORTNAME:-${MOODLE_SITE_NAME}}"
        --agree-license
    )
    [ -n "${MOODLE_SUPPORT_EMAIL:-}" ] && args+=(--supportemail="${MOODLE_SUPPORT_EMAIL}")
    moodle_php admin/cli/install_database.php "${args[@]}" || die "the Moodle install failed"

    # Settings that only apply to a new site: never touched again afterwards.
    local -a cfg=()
    [ -n "${MOODLE_NOREPLY_ADDRESS:-}" ] && cfg+=("noreplyaddress=${MOODLE_NOREPLY_ADDRESS}")
    [ -n "${MOODLE_TIMEZONE:-}" ] && cfg+=("timezone=${MOODLE_TIMEZONE}")
    if [ -n "${MOODLE_SMTP_HOST:-}" ]; then
        cfg+=("smtphosts=${MOODLE_SMTP_HOST}${MOODLE_SMTP_PORT:+:${MOODLE_SMTP_PORT}}")
        cfg+=("smtpuser=${MOODLE_SMTP_USER:-}" "smtppass=${MOODLE_SMTP_PASSWORD:-}")
        cfg+=("smtpsecure=${MOODLE_SMTP_SECURITY:-}")
    fi
    local kv
    for kv in "${cfg[@]}"; do
        moodle_php admin/cli/cfg.php --name="${kv%%=*}" --set="${kv#*=}" >/dev/null \
            || warn "could not set ${kv%%=*}"
    done

    if [ "${generated}" = yes ]; then
        log "------------------------------------------------------------------"
        log "Administrator: ${MOODLE_ADMIN_USER}"
        log "Generated password: ${password}"
        log "Change it after your first login, or set MOODLE_ADMIN_PASSWORD."
        log "------------------------------------------------------------------"
    fi
}

upgrade_site() {
    local rc=0 out
    out="$(moodle_php admin/cli/upgrade.php --is-pending 2>&1)" || rc=$?
    case "${rc}" in
        0) return 0 ;;
        2) ;;
        *) printf '%s\n' "${out}" >&2; die "Moodle cannot start (upgrade check failed with code ${rc})" ;;
    esac
    is_on "${MOODLE_AUTO_UPGRADE}" \
        || die "the database needs an upgrade and MOODLE_AUTO_UPGRADE is off; run: moodle-cli upgrade"
    if is_on "${MOODLE_BACKUP_BEFORE_UPGRADE}" && [ "${OKS_DB_BACKED_UP:-no}" != yes ]; then
        backup_dir_new
        backup_database
        backup_rotate
    fi
    log "Upgrading the Moodle database"
    moodle_php admin/cli/maintenance.php --enable >/dev/null || true
    moodle_php admin/cli/upgrade.php --non-interactive \
        || die "the database upgrade failed. The site stays in maintenance mode; backups are in ${OKS_DATA_STATE}/backups"
    moodle_php admin/cli/purge_caches.php >/dev/null || true
    moodle_php admin/cli/maintenance.php --disable >/dev/null || true
    log "Database upgrade finished"
}

# Extra language packs: installed when the list changes.
sync_langs() {
    local wanted="${MOODLE_EXTRA_LANGS:-}" stamp="${OKS_DATA_STATE}/langs"
    [ -n "${wanted}" ] || return 0
    [ "$(cat "${stamp}" 2>/dev/null)" = "${wanted}" ] && return 0
    log "Installing language packs: ${wanted}"
    if moodle_php "${OKS_PHP}/langs.php" "${MOODLE_CODE_DIR}" "${wanted}"; then
        echo "${wanted}" > "${stamp}"
    else
        warn "some language packs could not be installed; retrying at the next start"
    fi
}

sync_redis_cache() {
    [ -n "${MOODLE_REDIS_HOST:-}" ] || return 0
    local stamp="${OKS_DATA_STATE}/redis" wanted="${MOODLE_REDIS_HOST}:${MOODLE_REDIS_PORT:-6379}"
    [ "$(cat "${stamp}" 2>/dev/null)" = "${wanted}" ] && return 0
    if moodle_php "${OKS_PHP}/redis-cache.php" "${MOODLE_CODE_DIR}"; then
        echo "${wanted}" > "${stamp}"
    else
        warn "could not configure the Redis application cache; retrying at the next start"
    fi
}

# Scripts in /docker-entrypoint-init.d run once, after the first install.
run_init_scripts() {
    local marker="${OKS_DATA_STATE}/init-scripts-done" script
    [ -d /docker-entrypoint-init.d ] || return 0
    [ -f "${marker}" ] || [ -f "${MOODLE_CODE_DIR}/.user_scripts_initialized" ] && return 0
    for script in /docker-entrypoint-init.d/*; do
        [ -f "${script}" ] || continue
        case "${script}" in
            *.sh)  log "Running ${script}"; as_www bash "${script}" || die "${script} failed" ;;
            *.php) log "Running ${script}"; moodle_php "${script}" || die "${script} failed" ;;
            *)     warn "Ignoring ${script} (only .sh and .php are run)" ;;
        esac
    done
    touch "${marker}"
}

# HTTPS on APACHE_HTTPS_PORT when certificates are mounted at /certs, and
# for bitnami/moodle layouts (which always served 8443) with a self-signed one.
setup_tls() {
    OKS_TLS=off
    local crt key
    for crt in /certs/tls.crt /certs/server.crt; do
        key="${crt%.crt}.key"
        if [ -r "${crt}" ] && [ -r "${key}" ]; then
            MOODLE_TLS_CERT="${crt}" MOODLE_TLS_KEY="${key}" OKS_TLS=on
            break
        fi
    done
    if [ "${OKS_TLS}" = off ] && [ "${OKS_LAYOUT}" = bitnami ]; then
        local dir="${OKS_DATA_STATE}/tls"
        if [ ! -f "${dir}/tls.crt" ]; then
            mkdir -p "${dir}"
            chmod 0700 "${dir}"
            openssl req -x509 -newkey rsa:2048 -nodes -days 1825 -subj "/CN=${APACHE_SERVER_NAME}" \
                -addext "subjectAltName=DNS:${APACHE_SERVER_NAME},IP:127.0.0.1" \
                -keyout "${dir}/tls.key" -out "${dir}/tls.crt" 2>/dev/null \
                || { warn "could not create a self-signed certificate; HTTPS is off"; return 0; }
        fi
        MOODLE_TLS_CERT="${dir}/tls.crt" MOODLE_TLS_KEY="${dir}/tls.key" OKS_TLS=on
    fi
    export OKS_TLS MOODLE_TLS_CERT MOODLE_TLS_KEY
}
