# Global Apache settings for Moodle.

ServerName ${APACHE_SERVER_NAME}
ServerTokens ${APACHE_SERVER_TOKENS}
ErrorLog "|/usr/bin/cat"
ServerSignature Off
TraceEnable Off
GracefulShutdownTimeout 10

<IfModule mpm_prefork_module>
    ServerLimit             ${APACHE_MAX_REQUEST_WORKERS}
    MaxRequestWorkers       ${APACHE_MAX_REQUEST_WORKERS}
    StartServers            2
    MinSpareServers         2
    MaxSpareServers         8
    MaxConnectionsPerChild  1000
</IfModule>

# Health checks from Docker would otherwise fill the access log.
SetEnvIf Request_URI "^/_oksigenia/health$" moodle_nolog
