<?php
// Writes Moodle's config.php from the environment (native layout), or adds
// the include of the managed settings to an existing config.php.
//
// Usage:
//   php write-config.php native  <code-dir>   generate config.php from env
//   php write-config.php foreign <code-dir>   keep config.php, add the include
//   php write-config.php managed <file>       generate the managed settings
//
// The managed settings file is regenerated at every start. It holds what
// the image controls (router, binary paths, proxy, Redis sessions, the
// Access plugin switch) and then loads /etc/moodle/config.d/*.php.

const MANAGED = '/etc/moodle/oksigenia.php';
const INCLUDE_LINE = "if (is_readable('/etc/moodle/oksigenia.php')) { require('/etc/moodle/oksigenia.php'); } // oksigenia/moodle";

function env(string $name, string $default = ''): string {
    $v = getenv($name);
    return ($v === false || $v === '') ? $default : $v;
}

function on(string $value): bool {
    return in_array(strtolower($value), ['on', 'yes', 'true', '1'], true);
}

function export_value($v): string {
    return var_export($v, true);
}

function write_atomic(string $file, string $content, int $mode = 0640): void {
    $tmp = $file . '.tmp-' . getmypid();
    if (file_put_contents($tmp, $content) === false || !chmod($tmp, $mode) || !rename($tmp, $file)) {
        @unlink($tmp);
        fwrite(STDERR, "cannot write $file\n");
        exit(1);
    }
}

[$mode, $target] = [$argv[1] ?? '', $argv[2] ?? ''];

if ($mode === 'native') {
    $dbtype = env('MOODLE_DB_TYPE', 'mariadb');
    $dboptions = [
        'dbpersist' => 0,
        'dbport' => (int) env('MOODLE_DB_PORT'),
        'dbsocket' => '',
    ];
    if ($dbtype !== 'pgsql') {
        $dboptions['dbcollation'] = env('MOODLE_DB_COLLATION', 'utf8mb4_unicode_ci');
    }
    $lines = [
        '<?php  // Moodle configuration file',
        '',
        '// Generated by oksigenia/moodle at every container start: edits here are lost.',
        '// Put your own settings in /etc/moodle/config.d/*.php (see the README).',
        '',
        'unset($CFG);',
        'global $CFG;',
        '$CFG = new stdClass();',
        '',
        '$CFG->dbtype    = ' . export_value($dbtype) . ';',
        "\$CFG->dblibrary = 'native';",
        '$CFG->dbhost    = ' . export_value(env('MOODLE_DB_HOST')) . ';',
        '$CFG->dbname    = ' . export_value(env('MOODLE_DB_NAME')) . ';',
        '$CFG->dbuser    = ' . export_value(env('MOODLE_DB_USER')) . ';',
        '$CFG->dbpass    = ' . export_value(env('MOODLE_DB_PASSWORD')) . ';',
        '$CFG->prefix    = ' . export_value(env('MOODLE_DB_PREFIX', 'mdl_')) . ';',
        '$CFG->dboptions = ' . export_value($dboptions) . ';',
        '',
        '$CFG->wwwroot   = ' . export_value(env('MOODLE_URL')) . ';',
        '$CFG->dataroot  = ' . export_value(env('MOODLE_DATA_DIR')) . ';',
        "\$CFG->admin     = 'admin';",
        '$CFG->directorypermissions = 02770;',
        '',
        INCLUDE_LINE,
        '',
        "require_once(__DIR__ . '/lib/setup.php');",
        '',
        '// There is no php closing tag in this file,',
        '// it is intentional because it prevents trailing whitespace problems!',
        '',
    ];
    write_atomic("$target/config.php", implode("\n", $lines));
    exit(0);
}

if ($mode === 'foreign') {
    $file = "$target/config.php";
    $src = file_get_contents($file);
    if ($src === false) {
        fwrite(STDERR, "cannot read $file\n");
        exit(1);
    }
    if (str_contains($src, '/etc/moodle/oksigenia.php')) {
        exit(0);
    }
    $count = 0;
    $src = preg_replace('/^(\s*require(_once)?\s*\(?\s*(__DIR__|dirname\(__FILE__\))\s*\.\s*[\'"]\/lib\/setup\.php)/m',
        INCLUDE_LINE . "\n$1", $src, 1, $count);
    if ($count !== 1) {
        fwrite(STDERR, "$file: could not find the require of lib/setup.php\n");
        exit(1);
    }
    // Keep the original outside the web root's reach (.oksigenia is never served).
    $backup = "$target/.oksigenia/config.php.pre-oksigenia";
    if (!file_exists($backup)) {
        @mkdir(dirname($backup), 0770, true);
        copy($file, $backup);
        chmod($backup, 0640);
    }
    write_atomic($file, $src);
    exit(0);
}

if ($mode === 'managed') {
    $lines = [
        '<?php',
        '// Generated by oksigenia/moodle at every container start. Do not edit.',
        '// Your own settings go in /etc/moodle/config.d/*.php.',
        '',
        '$CFG->routerconfigured = true;',
        "\$CFG->pathtophp = '/usr/local/bin/php';",
        "\$CFG->pathtodu = '/usr/bin/du';",
        "\$CFG->pathtogs = '/usr/bin/gs';",
        "\$CFG->pathtopdftoppm = '/usr/bin/pdftoppm';",
    ];
    $url = env('MOODLE_URL');
    if ($url !== '' && env('OKS_LAYOUT') !== 'native') {
        // Native config.php already has it; a foreign one may build it from the Host header.
        $lines[] = '$CFG->wwwroot = ' . export_value($url) . ';';
    }
    $sslproxy = strtolower(env('MOODLE_SSL_PROXY', 'auto'));
    if ($sslproxy === 'auto') {
        // TLS terminated by a proxy in front of the container.
        $sslproxy = (str_starts_with($url, 'https://') && env('OKS_TLS') !== 'on'
            && env('OKS_LAYOUT') === 'native') ? 'on' : 'off';
    }
    if (on($sslproxy)) {
        $lines[] = '$CFG->sslproxy = true;';
    }
    if (on(env('MOODLE_REVERSE_PROXY', 'no'))) {
        $lines[] = '$CFG->reverseproxy = true;';
    }
    if (env('MOODLE_REDIS_HOST') !== '') {
        $lines[] = "\$CFG->session_handler_class = '\\core\\session\\redis';";
        $lines[] = '$CFG->session_redis_host = ' . export_value(env('MOODLE_REDIS_HOST')) . ';';
        $lines[] = '$CFG->session_redis_port = ' . (int) env('MOODLE_REDIS_PORT', '6379') . ';';
        if (env('MOODLE_REDIS_PASSWORD') !== '') {
            $lines[] = '$CFG->session_redis_auth = ' . export_value(env('MOODLE_REDIS_PASSWORD')) . ';';
        }
        $lines[] = "\$CFG->session_redis_prefix = 'mdl_sess_';";
        $lines[] = '$CFG->session_redis_acquire_lock_timeout = 120;';
        $lines[] = '$CFG->session_redis_lock_expire = 7200;';
        $lines[] = '$CFG->session_redis_serializer_use_igbinary = true;';
    }
    if (env('OKS_ACCESS_PRESENT') === 'yes') {
        $lines[] = "\$CFG->forced_plugin_settings['local_oksigeniaaccess']['enabled'] = "
            . (on(env('OKSIGENIA_ACCESS', 'off')) ? '1' : '0') . ';';
    }
    $lines[] = '';
    $lines[] = "foreach (glob('/etc/moodle/config.d/*.php') ?: [] as \$oksigeniafile) {";
    $lines[] = '    require($oksigeniafile);';
    $lines[] = '}';
    $lines[] = 'unset($oksigeniafile);';
    $lines[] = '';
    write_atomic($target, implode("\n", $lines), 0640);
    exit(0);
}

fwrite(STDERR, "usage: write-config.php native|foreign|managed <target>\n");
exit(2);
